version: '3.8'

services:
  master:
    image: 10.1.2.151:5000/master:latest
    ports:
      - "8888:8888"
    networks:
      - red-gRPC
    deploy:
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - red-gRPC
    deploy:
      placement:
        constraints:
          - node.role == manager

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - red-gRPC
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  red-gRPC:
    external: true
