version: '3.8'

services:
  master:
    image: 10.1.2.151:5000/master:latest
    ports:
      - "8888:8888"
    networks:
      - red-gRPC
    deploy:
      placement:
        constraints:
          - node.role == manager

  worker_python:
    image: 10.1.2.151:5000/worker_python
    networks:
      - red-gRPC
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role == worker

  worker_ruby:
    image: 10.1.2.151:5000/worker_ruby
    networks:
     - red-gRPC
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  worker_node:
    image: 10.1.2.151:5000/worker_node
    networks:
     - red-gRPC
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role == worker

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - red-gRPC
    deploy:
      placement:
        constraints:
          - node.role == manager

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - red-gRPC
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  red-gRPC:
    external: true

