version: '3.8'

services:
  master:
    build:
      context: .           # Contexto en la raíz del proyecto
      dockerfile: master/Dockerfile
    container_name: grpc_master
    ports:
      - "8888:8888"
    networks:
      - red-gRPC
    restart: always

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"       # Exposición del puerto de Redis
    networks:
      - red-gRPC
    restart: always

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"       # Puerto estándar MQTT
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 
    networks:
      - red-gRPC
    restart: always

networks:
  red-gRPC:
    external: true
