# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "RegisterWorkerRequest" do
  end
  add_message "RegisterWorkerResponse" do
    optional :worker_id, :string, 1
  end
  add_message "LogRequest" do
    optional :worker_id, :string, 1
    optional :sensor_id, :string, 2
    optional :freq, :float, 3
    optional :iteration, :int32, 4
  end
  add_message "LogResponse" do
    optional :status, :string, 1
  end
end

RegisterWorkerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("RegisterWorkerRequest").msgclass
RegisterWorkerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("RegisterWorkerResponse").msgclass
LogRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("LogRequest").msgclass
LogResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("LogResponse").msgclass
