# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: master.proto for package 'master'

require 'grpc'
require_relative 'master_pb'

module Master
  module Master
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'master.Master'

      rpc :RegisterWorker, RegisterWorkerRequest, RegisterWorkerResponse
      rpc :Log, LogRequest, LogResponse
    end

    Stub = Service.rpc_stub_class
  end
end
