# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: master.proto for package ''

require 'grpc'
require_relative 'master_pb'

module Master
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Master'

    rpc :RegisterWorker, RegisterWorkerRequest, RegisterWorkerResponse
    rpc :Log, LogRequest, LogResponse
  end

  Stub = Service.rpc_stub_class
end
